version: '3.8'

volumes:
  static:
  media:

services:
  backend:
    build:
      context: ./backend/wildberries
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/dist /app/result_build
    volumes:
      - ./frontend/result_build:/app/result_build

  nginx:
    build:
      context: ./infra
    volumes:
      - ./frontend/result_build:/usr/share/nginx/html/
      - static:/var/html/static
      - media:/var/html/media
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend