# Generated by Django 4.2 on 2025-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('rating', models.FloatField()),
                ('review_count', models.PositiveIntegerField()),
            ],
        ),
    ]
